### ISSUE TITLE
lbuild is outdated in image at 1.1.0. modm requires 1.4.0

### ISSUE THREAD

**Issue by strongly-typed** [modm-ext/docker-modm-build#2]
I am using the latest image

```
$ docker pull modm/modm-build:latest
latest: Pulling from modm/modm-build
Digest: sha256:7991e4510460b7e1b62779cc3f4cef37b1ba482c26dbd98e4dd53b59f2cc8450
Status: Image is up to date for modm/modm-build:latest
```

```
$ docker run -it --rm modm/modm-build:latest /bin/bash
# lbuild --version
lbuild 1.1.0
```

```
root@b388c7a65654:/build/src# lbuild build
/usr/local/lib/python3.6/dist-packages/lbuild/config.py:138: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if cache_node:
modm requires at least lbuild v1.4.0, please upgrade!
    pip install -U lbuild
```

When this is fixed no [manual update / installation of lbuild is necessary in the CI/CD](https://github.com/modm-io/modm/blob/develop/.circleci/config.yml#L12)

```
pip3 install -U lbuild
```
is necessary.

**Comment by strongly-typed** [comment]
Rebuilding the docker image will be enough:
```
docker run -it stronglytyped/docker-modm-build:latest /bin/bash
root@f2be35d71e27:/work# lbuild --version
lbuild 1.4.1
```
@salkinium Could you add please me to the docker organisation?

**Comment by salkinium** [comment]
Added you. The build can take 30mins and when I find a bug during a PR, I don’t want to wait that long. So I’d still leave the `pip3 install -U lbuild` in there, it only adds 1s build time or so per container.

**Comment by strongly-typed** [comment]
Docker hub is now updated and works for me.

Updates to lbuild shall trigger a rebuild of the docker container?!

`pip3 install -U lbuild` in the CI is OK for me, but we will not see if the container is not at the latest version. Maybe add a warning in the CI that pip updated lbuilld?
