### ISSUE TITLE
Missing Scons Installation

### ISSUE THREAD

**Issue by se-bi** [modm-ext/docker-modm-build#3]
Scons is missing in the latest docker-image.

You might want to add `scons` or `scons3` in the Dockerfile to the package list.

From an internal CI run:
```
$ scons --version
SCons import failed. Unable to find engine files in:
  /usr/local/lib/python3.6/dist-packages/scons-3.0.1
  /usr/local/lib/python2.7/dist-packages/scons-3.0.4
  /usr/local/lib/scons-3.0.4
  /usr/lib/scons-3.0.4
  /usr/local/lib/scons-3.0.4
  /usr/local/lib/python2.7/site-packages/scons-3.0.4
  /usr/local/lib/python2.7/site-packages/scons-3.0.4
  /usr/lib/scons-3.0.4
  /usr/local/lib/python2.7/dist-packages/scons
  /usr/local/lib/scons
  /usr/lib/scons
  /usr/local/lib/scons
  /usr/local/lib/python2.7/site-packages/scons
  /usr/local/lib/python2.7/site-packages/scons
  /usr/lib/scons
Traceback (most recent call last):
  File "/usr/local/bin/scons", line 195, in <module>
    import SCons.Script
ImportError: No module named SCons.Script
ERROR: Job failed: exit code 1
```

**Comment by salkinium** [comment]
No, scons is installed via the two requirements.txt. We explicitly set the `SCONS_LIB_DIR` in the CI scripts:

```yml
variables:
  LANG: "en_US.UTF-8"
  SCONS_LIB_DIR: "/usr/local/lib/python3.6/dist-packages/scons-3.0.1"
  SCONSFLAGS: "-j3"
```

I think the original intend was to test both SCons2 and SCons3, but we never bothered to do that.

**Comment by se-bi** [comment]
`scons-3.0.1` hard-coded is nice

https://pypi.org/project/scons/

**Comment by salkinium** [comment]
🙈 lalalala 🙉
.oO( How is this even working in CircleCI?!? )

**Comment by salkinium** [comment]
Docker Hub rebuilt our image, I'm not sure why…

> scons-3.0.1 hard-coded is nice

Yeah, that's not good. I don't fully understand why we need to set `SCONS_LIB_DIR` at all.

**Comment by salkinium** [comment]
> The issue is that the scons script it's being executed by default with python 2.7 although it has been installed with python 3.5. So in this line it is detecting the version of 2.7 instead of the good one which in this case 3.5.

**Comment by se-bi** [comment]
> Docker Hub rebuilt our image, I'm not sure why…

Was that automatically initiated?

(Ubuntu base got an update?)

> which in this case 3.5.

3.5 or 3.6? The difference should not matter, right?

**Comment by se-bi** [comment]
Somebody saw the inconvenience, with:

```
 -  SCONS_LIB_DIR: "/usr/local/lib/python3.6/dist-packages/scons-3.0.4" 
 +  SCONS_LIB_DIR: "/usr/local/lib/python3.6/dist-packages/scons"
```

it will find scons:

```
$ ls -ahl /usr/local/lib/python3.6/dist-packages/scons || true
total 12K
drwxr-sr-x  3 root staff 4.0K Jan 25 13:13 .
drwxrwsr-x  1 root staff 4.0K Jan 25 16:17 ..
drwxr-sr-x 10 root staff 4.0K Jan 25 13:13 SCons
$ scons --version
SCons by Steven Knight et al.:
	script: v3.0.4.3a41ed6b288cee8d085373ad7fa02894e1903864, 2019-01-20 22:51:36, by bdeegan on kufra
	engine: v3.0.4.3a41ed6b288cee8d085373ad7fa02894e1903864, 2019-01-20 22:51:36, by bdeegan on kufra
	engine path: ['/usr/local/lib/python3.6/dist-packages/scons/SCons']
Copyright (c) 2001 - 2019 The SCons Foundation
Job succeeded
```

**Comment by strongly-typed** [comment]
Rebuilding was initiated by me :-O Expected nothing bad. Sorry for the inconvenience caused.

I rebuilt because lbuild was outdated. Just saw now that the issues comes from the docker image. Was investigating our CI ...

Probably, it should build automatically (on a staging branch) to have problems like this pop up earlier.

The current image does not yet work. Sebi's fix works for me. Shall I update?

**Comment by se-bi** [comment]
> I rebuilt because lbuild was outdated.

And with several other updates, SCons changed its engine and removed the version number from the path, which is good regarding future updates.
But question remains, why SCons does not run from a pip installation without setting this `SCONS_LIB_DIR`.

> The current image does not yet work.

What is not working yet?
The RCA internal stuff is building fine, again.

For me now, only further depending images need to be rebuild.

**Comment by strongly-typed** [comment]
> The RCA internal stuff is building fine, again.

You probably set the `SCONS_LIB_DIR` in the CI config. Until now, we do not do this in our CI.

```
Last login: Fri Jan 25 18:03:44 on ttys002
➜  ~ docker pull modm/modm-build:latest
latest: Pulling from modm/modm-build
Digest: sha256:de0cf3360b4e50fe835acdc67205c62db814640ff07f5edf2599377b00a9ac6b
Status: Image is up to date for modm/modm-build:latest
➜  ~ docker run -it --rm modm/modm-build:latest
root@d8cf699300df:/work# scons -v
SCons import failed. Unable to find engine files in:
  /usr/local/lib/python3.6/dist-packages/scons-3.0.4
  /usr/local/lib/python2.7/dist-packages/scons-3.0.4
  /usr/local/lib/scons-3.0.4
  /usr/lib/scons-3.0.4
  /usr/local/lib/scons-3.0.4
  /usr/local/lib/python2.7/site-packages/scons-3.0.4
  /usr/local/lib/python2.7/site-packages/scons-3.0.4
  /usr/lib/scons-3.0.4
  /usr/local/lib/python2.7/dist-packages/scons
  /usr/local/lib/scons
  /usr/lib/scons
  /usr/local/lib/scons
  /usr/local/lib/python2.7/site-packages/scons
  /usr/local/lib/python2.7/site-packages/scons
  /usr/lib/scons
Traceback (most recent call last):
  File "/usr/local/bin/scons", line 195, in <module>
    import SCons.Script
ImportError: No module named SCons.Script
```

If I set it manually, it works
```
➜  docker-modm-build git:(master) docker run -it --rm b66917c32608
sroot@4ca91278e6d7:/work# scons -v
SCons import failed. Unable to find engine files in:
  /usr/local/lib/python3.6/dist-packages/scons-3.0.4
  /usr/local/lib/python2.7/dist-packages/scons-3.0.4
  /usr/local/lib/scons-3.0.4
  /usr/lib/scons-3.0.4
  /usr/local/lib/scons-3.0.4
  /usr/local/lib/python2.7/site-packages/scons-3.0.4
  /usr/local/lib/python2.7/site-packages/scons-3.0.4
  /usr/lib/scons-3.0.4
  /usr/local/lib/python2.7/dist-packages/scons
  /usr/local/lib/scons
  /usr/lib/scons
  /usr/local/lib/scons
  /usr/local/lib/python2.7/site-packages/scons
  /usr/local/lib/python2.7/site-packages/scons
  /usr/lib/scons
Traceback (most recent call last):
  File "/usr/local/bin/scons", line 195, in <module>
    import SCons.Script
ImportError: No module named SCons.Script
root@4ca91278e6d7:/work# export SCONS_LIB_DIR=/usr/local/lib/python3.6/dist-packages/scons
root@4ca91278e6d7:/work# scons -v
SCons by Steven Knight et al.:
	script: v3.0.4.3a41ed6b288cee8d085373ad7fa02894e1903864, 2019-01-20 22:51:36, by bdeegan on kufra
	engine: v3.0.4.3a41ed6b288cee8d085373ad7fa02894e1903864, 2019-01-20 22:51:36, by bdeegan on kufra
	engine path: ['/usr/local/lib/python3.6/dist-packages/scons/SCons']
Copyright (c) 2001 - 2019 The SCons Foundation
root@4ca91278e6d7:/work#
```

In my image, there is no `/usr/local/lib/python3.6/dist-packages/scons-3.0.4` directory.

I will change this now. In the progress of a local test build ...

**Comment by salkinium** [comment]
> I rebuilt because lbuild was outdated.

I have added a webhook to lbuild so that Docker Hub rebuilds the container when a push happens to the lbuild repo.

**Comment by salkinium** [comment]
By moving the environment variables into this Docker container, we can eliminate them from the CI setup, which is nice: https://github.com/modm-io/modm/pull/155
